version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: ./contents/go/Dockerfile
    volumes:
        - ./app/:/go/src/app
    tty: true
  db:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_mysql8_development'